### ISSUE TITLE
Restarting local instance - without any ssh

### ISSUE THREAD

**Issue by Jagdeep1** [Tjatse/elasticsearch-watchdog#1]
HI,

I find this module very interesting. May be I am still not able to get the complete understanding but I am still wondering how to restart the local instance of elasticsearch.
I want to run Elasticsearch and watchdog on same server and  just o re-start elatsicsearch if it stop responding. I think ssh configuration is not required for this kind of requirement.
How can I achieve this?

Thanks in advance

JS

**Comment by Tjatse** [comment]
Hi, JS, actually, I am using this module to manage the remote ElasticSearch cluster (master, load balance and data nodes) - auto restart when the ES node is unresponsive or standing alone, I've never considered local env..:p
But I am glad to add the feature, maybe tomorrow ;)

**Comment by Jagdeep1** [comment]
Thanks for you prompt response :)

It will be great if you add this feature.

I find this module interesting but I am wondering why it has not yet got enough traction.

**Comment by Tjatse** [comment]
Heh, welcome.
You're right, there is no other one yet, so I wrote it on my own. People still wanna do things by themselves, especially manage such a ES cluster which is full of nodes, may be they do not believe a "DOG" can do this better.

**Comment by Tjatse** [comment]
@Jagdeep1 v0.1.4 is bumped. [docs](https://github.com/Tjatse/elasticsearch-watchdog#configuration).
Please give it a whirl and let me known the result. :p

**Comment by Jagdeep1** [comment]
In your example you have still mentioned ssh, I am not sure why ssh is still required if its a local setup(everything on same server). We just need to give path of ES setup or if it is a service then we have to execute start service command `service elasticsearch restart`

In my case, I have given localhost, watching is fine but it fails to start ES if it is killed.
`watchdog.name: single-node
watchdog.frequency: critical
nodes.elasticsearch: ["127.0.0.1"]
nodes:
  ssh:
    - host:     127.0.0.1
      es_stop:  kill -9 `cat /Desktop/elasticsearch-1.4.0/pid`
      es_start: /Desktop/elasticsearch-1.4.0/bin/elasticsearch -d -p /Desktop/elasticsearch-1.4.0/pid
http.wait: 5m
http.retry: 3`

**Comment by Tjatse** [comment]
@Jagdeep1 ssh is just a data structure, never mind.
`127.0.0.1`, `0.0.0.0` and `localhost` are not supported, 'Cause in some cases, there are two or three network adapters on one server, e.g. `local`, `ethernet`...
You'd run `ifconfig` to fetch your local IP address, e.g. `192.168.1.130`, and make sure ES bind to that address (head over to [http://localhost:9200/_cluster/state](http://localhost:9200/_cluster/state) to [verify](https://github.com/Tjatse/elasticsearch-watchdog#configuration)).
```YAML
watchdog.name: single-node 
watchdog.frequency: critical 
nodes.elasticsearch: ["192.168.1.130"] 
nodes: 
  ssh: 
    - host: 192.168.130 
      es_stop: kill -9 "cat /Desktop/elasticsearch-1.4.0/pid"
      es_start: /Desktop/elasticsearch-1.4.0/bin/elasticsearch -d -p /Desktop/elasticsearch-1.4.0/pid http.wait: 5m 
http.retry: 3
```
